### PR TITLE
Update REQUIRE to have a max Julia version

### PR DESCRIPTION
**Pull request by IainNZ**
So it won't be installable with Pkg.add on Julia 0.4 and onwards.

Would be great to change the Github repo description too to something indicating the deprecated nature of the package.

### CODE REVIEW

**Comment by WestleyArgentum** [comment]
Lol, it appears travis is turned on even though there are no tests

**Comment by WestleyArgentum** [comment]
I don't have permissions to change the repo description... I think @stuinzuri might be the person that could figure that out

**Comment by WestleyArgentum** [comment]
Should I tag a new version? Or is there something special you do to deprecate packages? (There's already a deprecation warning in the code, so that should be ok)

**Comment by IainNZ** [comment]
Not terrible if can't, it'll still show a deprecation warning on pkg.julialang once I add a max version to the tagged versions.

I'll do it, don't worry

**Pull request merged**
